notifications:
  email: false

env:
  - ELECTRON_CACHE=$HOME/.cache/electron

os:
  - osx
  - linux
language: node_js
node_js: "8"

cache:
  directories:
    - node_modules
    - app/node_modules
    - tests/node_modules
    - $HOME/.cache/electron

install:
  - npm install
  - npm run rebuild
  - cd ./tests/
  - npm install
  - cd ..

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3;
    fi

script:
  - cd ./tests/
  - npm test
  - cd ..
  - if [ ! -z "$TRAVIS_TAG" ]; then npm run release; fi


#deploy:
#  provider: releases
#  api_key:
#    secure: RNbGl8IGSI4jJxdz3f7wj8c1oAQZZ8ewDkK/pjjTimxXbmRUKgeV1/GSkJOxOCmWKXRvYq1/qPYjW2nE99dpg9fd9+q+NxaIMeEOty6ZtNLXRvut46yqhsJIY8Hy2lzFbTSzJ3crUwCLPD1m4NdXPHvMzXiGO+BFYtrwiCsVcg6VDGlj7x2vkfaux16VCbuJzPqVoslTzVmFE8nwCU8zFudvGyWJttn5PqLit1OZ6NB+5T+haBN+y8zLW1q7XuULFkz5OEoaBz3l/tW54sXKeopOm7ccRSMsk4oZXjn12Vu9cErc22zX4zw6OlWHDWecNShcxOoOPmNQqoPyzGqeGqRqduwDcKYoAgPCLNgE2x9aAwfOrGJlv2YSlTzKF5c/ocQGrvdm8wUXS6XiEKRyGu9g2ljMW2I2qnBPbJjTFNCxLCmvmZVZHf182K6+CbHLdrLVi5uWRo7aypdi0t9+FmZAA0btJw27+v8qnOeaQFuU2mfwMbyTMUc3+5DlLsXR2FDY9weokptHimNtbJjgx3kxFvBSJCpIN4YpOwFJ+mlXXOf4l23I3RMaxKUSKWQE2YI3r+WJiVW9YcN9DctXzOMxjHFVSCiEtiAdAAjbmvafWdE5dm+ojA70P3HpwLVHA0pP8/KkRjXcIajfZ/l0vtOkGYufhQRSmgmY14iWn4A=
#  file:
#    - dist/*.AppImage
#    - dist/*.dmg
#    - dist/*.zip
#    - dist/*.exe
#  file_glob: true
#  skip_cleanup: true
#  on:
#    repo: beakerbrowser/beaker
#    tags: true
