export default {
  createEventStream: 'readable',
  refreshState: 'promise',
  getState: 'promise',
  getTabState: 'promise',
  createTab: 'promise',
  loadURL: 'promise',
  closeTab: 'promise',
  setActiveTab: 'promise',
  reorderTab: 'promise',
  showTabContextMenu: 'promise',
  showLocationBarContextMenu: 'promise',
  goBack: 'promise',
  goForward: 'promise',
  stop: 'promise',
  reload: 'promise',
  resetZoom: 'promise',
  toggleLiveReloading: 'promise',
  showInpageFind: 'promise',
  hideInpageFind: 'promise',
  setInpageFindString: 'promise',
  moveInpageFind: 'promise',
  showMenu: 'promise',
  toggleMenu: 'promise',
  focusShellWindow: 'promise'
}